### PR TITLE
updated documentation

### PR DESCRIPTION
**Pull request by neelsoumya**
updated documentation

### CODE REVIEW

**Comment by neelsoumya** [comment]
updated documentation

**Review by tombisho — CHANGES_REQUESTED** [review]
Again, this is great, thank you.

To match the client, please can you provide a little more details on installing the package in Opal:  https://opaldoc.obiba.org/en/latest/web-user-guide/administration/datashield.html#add-package

**Review by neelsoumya — COMMENTED** [review]
Thanks! I just added the link

**Review by tombisho — COMMENTED** [review]
Great! Thanks

**Pull request closed without merging**
